SEED: 2023
output_dir: 'data3d/experiments/pretrain/shapenetcore/data.openshape-pc1024.g64.s32-csc.keep.sa-mae.color.0.05-csc.l1.txt.img.openclip'
tfboard_log_dir: null # 'data/TFBoard/xxx'
checkpoint: null
checkpoint_strict_load: false # true, false
checkpoint_ensemble: 1

TRAIN:
  val_batch_size: 128

VAL_DATASET:
  dataset_names: ['modelnet10', 'modelnet40', 'scanobjectnn_nobg', 'scanobjectnn', 'scanobjectnn_hardest', 'objaverse_lvis']
  label_embed_dir: 'data3d/pretrain_dataset/label_embeds'

  dataset_cfgs:
    modelnet10:
      num_categories: 10
      split: test  # train, test
      data_root: 'data3d/recon_datasets/ModelNet/modelnet40_normal_resampled'
      input_num_points: 1024
      output_num_points: 1024
      y_up: True
      fps_sample: False
      use_color: True
      color_pad_value: 0.0
      normalize: True
      random_z_rotate: False
      augment: False

    modelnet40:
      num_categories: 40
      split: test  # train, test
      data_root: 'data3d/recon_datasets/ModelNet/modelnet40_normal_resampled'
      input_num_points: 8192
      output_num_points: 1024
      y_up: True
      fps_sample: False
      use_color: True
      color_pad_value: 0.0
      normalize: True
      random_z_rotate: False
      augment: False
    
    scanobjectnn_nobg:
      num_categories: 15
      split: test  # train, test
      no_bg: True
      hardest_setup: False
      data_root: 'data3d/recon_datasets/ScanObjectNN'
      output_num_points: 1024
      y_up: True
      fps_sample: False
      use_color: True
      color_pad_value: 0.0
      normalize: True
      random_z_rotate: False
      augment: False
    
    scanobjectnn:
      num_categories: 15
      split: test  # train, test
      no_bg: False
      hardest_setup: False
      data_root: 'data3d/recon_datasets/ScanObjectNN'
      output_num_points: 1024
      y_up: True
      fps_sample: False
      use_color: True
      color_pad_value: 0.0
      normalize: True
      random_z_rotate: False
      augment: False

    scanobjectnn_hardest:
      num_categories: 15
      split: test  # train, test
      no_bg: False
      hardest_setup: True
      data_root: 'data3d/recon_datasets/ScanObjectNN'
      output_num_points: 1024
      y_up: True
      fps_sample: False
      use_color: True
      color_pad_value: 0.0
      normalize: True
      random_z_rotate: False
      augment: False

    objaverse_lvis:
      data_ids_file: 'data3d/OpenShape/meta_data/split/lvis.json'
      data_dir: 'data3d/OpenShape/objaverse-processed/merged_for_training_final/Objaverse'
      output_num_points: 1024
      y_up: True
      fps_sample: False
      use_color: True
      normalize: True
      random_z_rotate: False
      augment: False
  
MODEL:
  model_class: 'PCPretrainModel'
  clip_model: 'openclip'  # clip, openclip

  transformer_config:
    num_groups: 64
    num_groups_multiobj: 64
    group_size: 32
    input_size: 6
    hidden_size: 384
    num_heads: 6
    depth: 12

    cross_attn_input: 'post' # pre, post, extra
    cross_attn_layers: null

    mask_ratio: 0.
    mask_type: rand # rand, block

    drop_path_rate: 0.

    detach_enc_dec: False
    csc_skip_dec_sa: False

  mae_decoder_config:
    depth: 4
    num_heads: 6
    drop_path_rate: 0.1

  cross_modal_config:
    img_ft_size: 1280
    txt_ft_size: 1280

  obj_decoder_config:
    num_objects: 30

  ref_decoder_config:
    txt_ft_size: 1280
    max_txt_len: 77
    multiscale_pc_layers: [12]

  loss_config:
    mae_loss_weight: 1.0
    mae_color_loss_weight: 0.05

    csc_loss_type: 'l1' # l1, contrastive
    csc_temperature: 0.1
    csc_txt_loss_weight: 1.
    csc_img_loss_weight: 1.

    obj_loss_weight: 1.0
    ref_loss_weight: 1.0

    ref_loss:
      focal_loss: False
      bce_loss_weight: 1.0
      dice_loss_weight: 1.0
    
